eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8768
spring:
  application:
    name: eshop-one-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://172.27.35.3:3306/eshop
    username: root
    password: root


feign:
    hystrix:
      enabled: true
